/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.serverproject;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author kacpe
 */
public class ServerProject extends javax.swing.JFrame {
    
    int x1 = -1;
    int y1 = -1;
    int x2 = -1;
    int y2 = -1;
    int count = 0;
    //JButton jb[] = new JButton[2];
    ArrayList<JButton> jb = new ArrayList<JButton>();

    /**
     * Creates new form ServerProject
     */
    public ServerProject() {
        initComponents();
//        jPanel1.setOpaque(false);
        trans(jButton33);
        trans(jButton34);
        trans(jButton35);
        trans(jButton36);
        trans(jButton37);
        trans(jButton38);
        trans(jButton39);
        trans(jButton40);
        trans(jButton41);
        trans(jButton42);
        trans(jButton43);
        trans(jButton44);
        trans(jButton45);
        trans(jButton46);
        trans(jButton47);
        trans(jButton48);
        trans(jButton49);
        trans(jButton50);
        trans(jButton51);
        trans(jButton52);
        trans(jButton53);
        trans(jButton54);
        trans(jButton55);
        trans(jButton56);
        trans(jButton57);
        trans(jButton58);
        trans(jButton59);
        trans(jButton60);
        trans(jButton61);
        trans(jButton62);
        trans(jButton63);
        trans(jButton64);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 640));
        setMinimumSize(new java.awt.Dimension(620, 640));
        setPreferredSize(new java.awt.Dimension(620, 640));
        setSize(new java.awt.Dimension(620, 640));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 470, 50, 50);
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 470, 50, 50);
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 470, 50, 50);
        jPanel1.add(jButton4);
        jButton4.setBounds(240, 470, 50, 50);
        jPanel1.add(jButton5);
        jButton5.setBounds(310, 470, 50, 50);
        jPanel1.add(jButton6);
        jButton6.setBounds(390, 470, 50, 50);
        jPanel1.add(jButton7);
        jButton7.setBounds(460, 470, 50, 50);
        jPanel1.add(jButton8);
        jButton8.setBounds(540, 470, 50, 50);
        jPanel1.add(jButton9);
        jButton9.setBounds(10, 90, 50, 50);
        jPanel1.add(jButton10);
        jButton10.setBounds(90, 90, 50, 50);
        jPanel1.add(jButton11);
        jButton11.setBounds(160, 90, 50, 50);
        jPanel1.add(jButton12);
        jButton12.setBounds(240, 90, 50, 50);
        jPanel1.add(jButton13);
        jButton13.setBounds(310, 90, 50, 50);
        jPanel1.add(jButton14);
        jButton14.setBounds(390, 90, 50, 50);
        jPanel1.add(jButton15);
        jButton15.setBounds(460, 90, 50, 50);
        jPanel1.add(jButton16);
        jButton16.setBounds(540, 90, 50, 50);

        jButton17.setBackground(new java.awt.Color(0, 51, 51));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(10, 540, 50, 50);
        jPanel1.add(jButton18);
        jButton18.setBounds(540, 540, 50, 50);
        jPanel1.add(jButton19);
        jButton19.setBounds(10, 10, 50, 50);
        jPanel1.add(jButton20);
        jButton20.setBounds(540, 10, 50, 60);
        jPanel1.add(jButton21);
        jButton21.setBounds(80, 540, 72, 50);
        jPanel1.add(jButton22);
        jButton22.setBounds(460, 540, 72, 50);
        jPanel1.add(jButton23);
        jButton23.setBounds(90, 10, 50, 50);
        jPanel1.add(jButton24);
        jButton24.setBounds(460, 10, 50, 50);
        jPanel1.add(jButton25);
        jButton25.setBounds(160, 540, 50, 50);
        jPanel1.add(jButton26);
        jButton26.setBounds(390, 540, 50, 50);
        jPanel1.add(jButton27);
        jButton27.setBounds(160, 10, 50, 50);
        jPanel1.add(jButton28);
        jButton28.setBounds(390, 10, 50, 50);
        jPanel1.add(jButton29);
        jButton29.setBounds(310, 540, 50, 50);
        jPanel1.add(jButton30);
        jButton30.setBounds(310, 10, 50, 50);
        jPanel1.add(jButton31);
        jButton31.setBounds(230, 540, 60, 50);
        jPanel1.add(jButton32);
        jButton32.setBounds(240, 10, 50, 50);

        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);
        jButton33.setBounds(10, 160, 60, 60);
        jPanel1.add(jButton34);
        jButton34.setBounds(80, 160, 60, 60);
        jPanel1.add(jButton35);
        jButton35.setBounds(160, 160, 60, 60);
        jPanel1.add(jButton36);
        jButton36.setBounds(230, 160, 60, 60);
        jPanel1.add(jButton37);
        jButton37.setBounds(310, 160, 60, 60);
        jPanel1.add(jButton38);
        jButton38.setBounds(380, 160, 60, 60);
        jPanel1.add(jButton39);
        jButton39.setBounds(460, 160, 60, 60);
        jPanel1.add(jButton40);
        jButton40.setBounds(530, 160, 60, 60);
        jPanel1.add(jButton41);
        jButton41.setBounds(10, 240, 60, 60);
        jPanel1.add(jButton42);
        jButton42.setBounds(80, 240, 60, 60);
        jPanel1.add(jButton43);
        jButton43.setBounds(160, 240, 60, 60);
        jPanel1.add(jButton44);
        jButton44.setBounds(230, 240, 60, 60);
        jPanel1.add(jButton45);
        jButton45.setBounds(310, 240, 60, 60);
        jPanel1.add(jButton46);
        jButton46.setBounds(380, 240, 60, 60);
        jPanel1.add(jButton47);
        jButton47.setBounds(460, 240, 60, 60);
        jPanel1.add(jButton48);
        jButton48.setBounds(530, 240, 60, 60);
        jPanel1.add(jButton49);
        jButton49.setBounds(10, 310, 60, 60);
        jPanel1.add(jButton50);
        jButton50.setBounds(80, 310, 60, 60);
        jPanel1.add(jButton51);
        jButton51.setBounds(160, 310, 60, 60);
        jPanel1.add(jButton52);
        jButton52.setBounds(230, 310, 60, 60);
        jPanel1.add(jButton53);
        jButton53.setBounds(310, 310, 60, 60);
        jPanel1.add(jButton54);
        jButton54.setBounds(380, 310, 60, 60);
        jPanel1.add(jButton55);
        jButton55.setBounds(460, 310, 60, 60);
        jPanel1.add(jButton56);
        jButton56.setBounds(530, 310, 60, 60);
        jPanel1.add(jButton57);
        jButton57.setBounds(10, 390, 60, 50);
        jPanel1.add(jButton58);
        jButton58.setBounds(80, 390, 60, 60);
        jPanel1.add(jButton59);
        jButton59.setBounds(161, 390, 60, 60);
        jPanel1.add(jButton60);
        jButton60.setBounds(230, 390, 60, 60);
        jPanel1.add(jButton61);
        jButton61.setBounds(310, 390, 60, 50);
        jPanel1.add(jButton62);
        jButton62.setBounds(380, 390, 60, 50);
        jPanel1.add(jButton63);
        jButton63.setBounds(460, 390, 60, 50);
        jPanel1.add(jButton64);
        jButton64.setBounds(530, 390, 60, 50);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 610);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        count++;
        if(count==1){
            x1 = jButton1.getX();
            y1 = jButton1.getY();
            jb.add(jButton1);
            
        }else{
            x2 = jButton1.getX();
            y2 = jButton1.getY();
            jButton1.setLocation(x1, y1);
            jb.get(0).setLocation(x2, y2);
            jb.remove(0);
            count=0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
//        count++;
//        if(count==1){
//            x1 = jButton17.getX();
//            y1 = jButton17.getY();
//            jb.add(jButton17);
//            
//        }else{
//            x2 = jButton17.getX();
//            y2 = jButton17.getY();
//            jButton17.setLocation(x1, y1);
//            jb.get(0).setLocation(x2, y2);
//            jb.remove(0);
//            count=0;
//        }
        check(jButton17);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerProject().setVisible(true);
            }
        });
    }
    
    public static void trans(JButton jBt){
        jBt.setOpaque(false);
        jBt.setContentAreaFilled(false); //to make the content area transparent
        jBt.setBorderPainted(false); 
    }
    
    public void check(JButton jBt){
        count++;
        if(count==1){
            x1 = jBt.getX();
            y1 = jBt.getY();
            jb.add(jBt);
            
        }else{
            x2 = jBt.getX();
            y2 = jBt.getY();
            jBt.setLocation(x1, y1);
            jb.get(0).setLocation(x2, y2);
            jb.remove(0);
            count=0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
